# Generated by Django 4.2.7 on 2026-04-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(db_index=True, max_length=14, unique=True)),
                ('matriz_filial', models.CharField(blank=True, max_length=1)),
                ('razao_social', models.CharField(db_index=True, max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255)),
                ('situacao_cadastral', models.CharField(blank=True, db_index=True, max_length=2)),
                ('data_situacao_cadastral', models.DateField(blank=True, null=True)),
                ('motivo_situacao_cadastral', models.CharField(blank=True, max_length=2)),
                ('natureza_juridica', models.CharField(blank=True, db_index=True, max_length=4)),
                ('data_abertura', models.DateField(blank=True, db_index=True, null=True)),
                ('cnae_principal', models.CharField(blank=True, db_index=True, max_length=7)),
                ('cnaes_secundarios', models.TextField(blank=True)),
                ('porte_empresa', models.CharField(blank=True, max_length=2)),
                ('logradouro', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=255)),
                ('bairro', models.CharField(blank=True, max_length=120)),
                ('cep', models.CharField(blank=True, max_length=8)),
                ('municipio', models.CharField(blank=True, db_index=True, max_length=120)),
                ('uf', models.CharField(blank=True, db_index=True, max_length=2)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site_url', models.URLField(blank=True)),
                ('contatos_publicos', models.JSONField(blank=True, default=dict)),
                ('enrichment_source_urls', models.JSONField(blank=True, default=list)),
                ('enrichment_status', models.CharField(choices=[('pending', 'Pendente'), ('done', 'Concluido'), ('failed', 'Falhou')], default='pending', max_length=10)),
                ('enrichment_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa Receita',
                'verbose_name_plural': 'Empresas Receita',
                'ordering': ['-data_abertura', 'razao_social'],
            },
        ),
    ]
